### ISSUE TITLE
Incorrect Material You Dynamic Theming

### ISSUE THREAD

**Issue by abdalmoniem** [Anthonyy232/Paperize#13]
when I enable individual intervals with different intervals for the home screen and lock screen, the system seems to pickup the colors from the lock screen not the home screen, I guess because the lock screen wallpaper is applied after the home screen, which somehow messes with the Monet Engine.

the following screenshot shows that the color is picked from the lock screen

[<img src="https://github.com/Anthonyy232/Paperize/assets/11904264/5d5455d9-1366-40d9-aa2c-d8a36f18fa46" alt="Screenshot_2024-06-08-09-10-19-89_1b61703d69a62e7920e4dc1279b915d9.jpg" width="350"/>](https://github.com/Anthonyy232/Paperize/assets/11904264/5d5455d9-1366-40d9-aa2c-d8a36f18fa46)

here it should pick some orangeish / brownish color from the home screen, but i stead the color is greenish (picked from the lock screen)

currently I can fix it if I go to the android settings and change the colors to anything and then change it back to match the wallpaper.

**Comment by Anthonyy232** [comment]
Hi! I will look into this and probably push out an update tomorrow or the day after. This should be a quick fix of swapping the order around so that the lock screen is set first, and then the home screen. This makes more sense to me too -- the device's material theming should reflect the home wallpaper since that is where the icons live.

As an aside, this appears to me that the device's dynamic theming is based off whichever wallpaper is set most recent, rather than the home screen. For users who are only interested in setting the lock screen, this will cause their dynamic theming to change. That isn't something I can fix and is likely up to the Android team and OEMs/vendors. I will look into this but I'm quite sure there is no flag in WallpaperManager (Android's library to set wallpaper) to prevent alerting the Monet engine unfortunately.

**Comment by abdalmoniem** [comment]
hi, I'm using a OnePlus 12.

yes I tried this on my Samsung Tablet and I have the same issue. but I think Samsung has explicitly disabled the dynamic theming, since if I manually set the wallpaper (eg from the gallery), the colors don't change unless I go to the settings and change them.

**Comment by Anthonyy232** [comment]
The approach I had in mind appears to not work like I had expected, will need to experiment a bit more.

**Comment by Anthonyy232** [comment]
Just wanted to let you know that I still have this issue in mind, just away for the next two weeks so it's on pause a little.

**Comment by abdalmoniem** [comment]
sure, no problem. I'm looking into the issue as well, and will inform you if I find something ☺️

**Comment by Anthonyy232** [comment]
Sure! I'll say that in cases of setting both home screen and lock screen separately, when I set the lock screen I tried to set the previous home screen right after. I believe this works in principle but didn't work in my testing perhaps due to out of heap memory because of the fast use of 2 potentially large bitmaps. When I get back, I will see if using large heap would work, and if that would cause any  undesirable effects

**Comment by Anthonyy232** [comment]
Well, using large heap did not make things better. Still trying to figure out a way to implement a fix.

**Comment by Anthonyy232** [comment]
Hi, would you mind testing if this works? It worked when I was testing it on the emulator, but I don't have a real Pixel device to test this fix on. Really appreciate it, thanks!

https://github.com/Anthonyy232/Paperize/releases/tag/v1.6.0

**Comment by abdalmoniem** [comment]
Hello, I just tested the new release and it works flawlessly. Great job 👏 
What was the cause of the issue? 😅

Also I noticed there's no delay right now after changing the wallpaper, I guess the Alarm Manager made it a lot faster.

Appreciate your efforts and time 😊

**Comment by Anthonyy232** [comment]
Glad it worked out, thank you for your help and for bringing this issue up. Let me know if you encounter any further problems and I will try to fix them.

The cause of the issue is the same -- the Monet engine picks the dynamic theme from the last set wallpaper (either lock or home). To solve it, I simply set the home wallpaper again after the lock screen wallpaper is set to ensure the home screen would always be the latest one. Previously when I tried it, it didn't work because the async nature of my code closed the service before it would finish. I put it into the same coroutine scope and it worked.

If the user only chooses to set the home screen wallpaper, nothing changes. If they only set the lock screen wallpaper, the Monet engine will take the lock screen's color. I can't do anything about the latter due to Android 13/14/15's horrible permission handling that would require the app to request MANAGE_EXTERNAL_STORAGE just to get the user's wallpaper.
