### ISSUE TITLE
[Bug] On versions later than 2.0 wallpapers do not scale properly

### ISSUE THREAD

**Issue by fassdragon2** [Anthonyy232/Paperize#136]
**Describe the bug**
When I have Any version later than 2.0 installed wallpapers are zoomed in way to far on fill

**To Reproduce**
Steps to Reproduce:
1. Install version 2.1.0 or higher or update to said version
2. Use fill
3. go to home/lock screen to check

**Expected behavior**
To see most of the selected wallpaper(I use fill so that the wallpaper is not weird when in portrait mode)
Screenshot from 2.0.0
![Screenshot_20240906_113704_One UI Home](https://github.com/user-attachments/assets/af829cba-a943-4d87-9942-b0b7550f03bc)

**Screenshots**
Portrait
![Screenshot_20240906_112955_One UI Home](https://github.com/user-attachments/assets/99d0a4ad-cb31-42a1-b030-c6dd87029a21)
Landscape
![Screenshot_20240906_112946_One UI Home](https://github.com/user-attachments/assets/8f14784d-4b1a-44a3-96f6-d6a3e7982c81)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Tab S9 Ultra]
 - OS: [1UI 6.1]
 - Version [v2.1.0 or above]

**Additional context**
Fit works fine, stretch is also weird

**Comment by Anthonyy232** [comment]
Can you provide the wallpaper so I can do some testing?

**Comment by fassdragon2** [comment]
Sure, I do have the issue with all my wallpapers through so should I send them all?

**Comment by Anthonyy232** [comment]
Nah just give me one of them is fine

**Comment by fassdragon2** [comment]
Alr
![anime-1725417225](https://github.com/user-attachments/assets/509c1656-bd86-4358-b0fd-b8239eec963a)

**Comment by fassdragon2** [comment]
Also, not sure if it's a 2.0.0 thing but when a wallpaper is changed while in portrait it is zoomed in when going to landscape

**Comment by HypNotiQ4** [comment]
Also having this issue on my pixel tab, it's always in landscape & fill is super zoomed in

**Comment by Anthonyy232** [comment]
Okay, so basically, this happens because fill/stretch/fit changes the actual size of the image before applying it (to achieve the effect). So for example, when applying, it takes the width and scales the height based on height. So when switching orientation, there is no extra height in the image to use -- that's why it's zoomed in. 

I'm still trying to look, but there doesn't seem to be a concise fix for this. I will add a 'None' scaling option that does the same thing as how Google and Samsung handles their wallpapers. The downside to this is that portrait mode will look bad because it begin from the left so if you only have one home screen and the wallpaper designed to be centered, not much will be viewable. 
(If Repraze does not finish this, I will implement my own https://github.com/Anthonyy232/Paperize/pull/94)

This is the default behavior of Google Pixel and Samsung OneUI -- I tried to show the app version too but the IDE bugged out on me (it essentially acts the same if NONE scaling is applied)

https://github.com/user-attachments/assets/75511976-3fdf-4120-aacf-24626118bd1f
