### ISSUE TITLE
[FR] Change to Next Wallpaper Immediately

### ISSUE THREAD

**Issue by sakarie9** [Anthonyy232/Paperize#51]
A button is needed to change to the next wallpaper before the timer triggers. 

This allows users to manually switch to a new wallpaper at any time, without having to wait for the timer.

**Comment by Anthonyy232** [comment]
I will likely not add that, since it will clutter the UI even more. Currently there are three ways:

Remove the album and re-add it, toggle the changer to off and then on, or use the change wallpaper tile like below
![image](https://github.com/user-attachments/assets/ff997c66-0f40-49bd-ab92-e892802f32e8)

Really appreciate the suggestion though, thank you!

**Comment by sakarie9** [comment]
I didn't notice there is a wallpaper changer tile! It really meets my needs.

However, perhaps an app shortcut would be more intuitive and easier to use?

**Comment by Anthonyy232** [comment]
By an app shortcut, do you mean a widget? I am planning on adding that at some point, bit lazy though. If you mean a button inside the app, I may reconsider if I find a good place to put it -- currently don't see a nice way to put it in.

**Comment by sakarie9** [comment]
A long-click menu on the app icon, like the one shown below, can also be used to create pinned shortcuts.

![Image](https://developer.android.com/static/images/guide/topics/ui/shortcuts/pinned-shortcuts.png)

This would make it easy to perform actions such as "Change to next wallpaper".

**Comment by Anthonyy232** [comment]
Actually, i didn't know that. I will add that. Thanks!

**Comment by Anthonyy232** [comment]
Fixed in commit https://github.com/Anthonyy232/Paperize/commit/e95c923a6a8f293d0eba8c2374e2ef9393cfa5e6
