### ISSUE TITLE
Crash on selecting the whole internal storage

### ISSUE THREAD

**Issue by shuvashish76** [Anthonyy232/Paperize#54]
### Steps to reproduce:
1. Create a new album > Add folder > select the whole internal storage
2. It shows path 0, 1950 wallpapers
3. Click on it to view the wallpapers
App crashes

### Logs:
[PrivateBin link](https://privatebin.net/?b499af61b6df2e2c#-EBQWLAoEzFBz7LVzdiMzYRUwU5c35fNCXXC6ms7SB6pU),  logs are recorded with [LogFox](https://f-droid.org/packages/com.f0x1d.logfox/)

### Device details:
Android : 9
Model : Lenovo Tab4 8 plus (TB-8704X)
App version : 1.6.3 (28)

**Comment by Anthonyy232** [comment]
If it's not too much trouble to ask, are you able to record this? I'm not sure where the problem is. I'm not able to get much out of the log and also I was not able to reproduce the issue on an SDK 28 virtual tablet emulator. I suspect it may be due to some weird extension files are being picked up from the various subfolders. It could also be a vendor-specific problem.

**Comment by shuvashish76** [comment]
Screen recording?
<details><summary>Here</summary>
<p>

https://github.com/user-attachments/assets/e7000d62-9f18-4905-a8ab-1d7e95ea9456

</p>
</details>

**Comment by Anthonyy232** [comment]
Can I ask you to try this APK and see if the same crash occurs? Same deal -- signed APK in the zip file. Thanks!

[app-release.zip](https://github.com/user-attachments/files/16398320/app-release.zip)

**Comment by shuvashish76** [comment]
Thanks no such crashes & I can view all the images.
But it crashed few times _(exactly not sure how to reproduce this)_ while testing

Crash Logs:
```
FATAL EXCEPTION: main
Process: com.anthonyla.paperize, PID: 9766
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1826272 bytes
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 1826272 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1129)
	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4029)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
	... 7 more
```

**Comment by Anthonyy232** [comment]
Have you encountered this previously or just with the APK that I sent? 

To fix the previous issue, I reverted the one of the screen navigations back to GSON converting the list rather than type-safe navigating on a list. This is because the type-safe navigation still seems to have a bug if there is a large amount of items in a list which causes some instability. The GSON approach works better, albeit much slower. I imagine this crash is because there is just too much data being sent through the string (all 1950 wallpapers). Realistically, I don't think many people would have 1950 wallpapers so it's mostly a non-issue if I'm correct, but I'll see if I can fix this somehow, maybe breaking the string being sent up into smaller pieces may help, not sure.

**Comment by shuvashish76** [comment]
> Have you encountered this previously or just with the APK that I sent?

I'm not sure about it as it's an intermittent crash. Never experienced in official release maybe I've not tested it properly IDK. 🤷🏽

> Realistically, I don't think many people would have 1950 wallpapers so it's mostly a non-issue if I'm correct

For me those are mostly from
- `/storage/emulated/0/Android/data/io.github.muntashirakon.AppManager.debug/cache/images` appicons cache from [AppManager](https://t.me/s/AppManagerDebug) debug builds.
- `/storage/emulated/0/Android/data/org.forkgram.messenger/cache`channel/groups images cache from [Forkgram](https://f-droid.org/packages/org.forkgram.messenger/)

Yeah, they're mostly unimportant images.

**Comment by Anthonyy232** [comment]
I believe the issue is fixed in commit https://github.com/Anthonyy232/Paperize/commit/c15bea8b3777d70a6bcd24e84b047365080ec869

Would you care to test it?
[app-release.zip](https://github.com/user-attachments/files/16556866/app-release.zip)

Thanks!

**Comment by shuvashish76** [comment]
Thanks no crashes so far. I'll reopen if I experience in official stable releases.
